config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'home', to: "home#index"
  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'admin', to: 'admin#dashboard'
  get 'admin/books', to: 'admin#books'

  get 'dashboard', to:'user_dashboard#dashboard'
  get 'dashboard/purchases', to: "user_dashboard#purchases"

  get 'generate', to: "bills#generate", as: :generate_bill

  resources :products
  resources :plans
  resources :charges, only: [:new, :create]

  get 'payment_success', to: "charges#success", as: :success_payment

  get  'pricing', to: "pricing#index", as: :pricing
  resources :subscriptions

  get '/card/new' => "payment_methods#new_card", as: :add_payment_method
  post "/card" => "payment_methods#create_card", as: :create_payment_method
  get '/card/:id' => "payment_methods#show", as: :card
  delete '/card/:id' => "payment_methods#destroy", as: :remove_card
  get '/cards' => "payment_methods#cards", as: :cards
  post "/bank_account" => "payment_methods#add_bank_account", as: :add_bank_account
  get "/bank_account/:id" => "payment_methods#bank_account", as: :bank_account
end

app/views/layouts/profile/_actions.html.erb
<div class="dropdown is-right">

  <div class="dropdown-trigger">
    <button class="button is-primary" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>Profile</span>
      <span class="icon is-small">
        <i class="fa fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </div>

  <div class="dropdown-menu" id="dropdown-menu" role="menu">
    <div class="dropdown-content">
      <p class="dropdown-item">
        signed in as <strong><%= current_user.name %></strong>
      </p>

      <hr class="dropdown-divider">

      <%= link_to "Admin Dashboard", admin_path, class:"dropdown-item" if current_user.admin? %>

      <strong>
        <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
      </strong>

      <hr class="dropdown-divider">

      <%= link_to "Change profile", edit_user_registration_path, class: "dropdown-item" %>

      <%= link_to "Subcriptions", subscriptions_path, class: "dropdown-item"%>

      <hr class="dropdown-divider">

       <% if current_user.has_library_access? %>
        <p class="dropdown-item">
           <strong>active subcription</strong>
        </p>

        <%= link_to subscription_path(current_user.active_subcription) do %>
          <p class="active-subs">
            <%= current_user.active_subcription.plan.nickname %>
          </p>
        <% end %>

      <% else %>
        <%= link_to "Subscripe", pricing_path, class: "button is-success is-outlined is-fullwidth is-rounded"%>
      <% end %>

      <hr class="dropdown-divider">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
    </div>
  </div>

</div>