config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'home', to: "home#index"
  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'admin', to: 'admin#dashboard'
  get 'admin/books', to: 'admin#books'

  get 'dashboard', to:'user_dashboard#dashboard'
  get 'dashboard/purchases', to: "user_dashboard#purchases"

  get 'generate', to: "bills#generate", as: :generate_bill

  resources :products
  resources :plans
  resources :charges, only: [:new, :create]

  get 'payment_success', to: "charges#success", as: :success_payment

  get  'pricing', to: "pricing#index", as: :pricing
  resources :subscriptions

  get '/card/new' => "payment_methods#new_card", as: :add_payment_method
  post "/card" => "payment_methods#create_card", as: :create_payment_method
  get '/card/:id' => "payment_methods#show", as: :card
  delete '/card/:id' => "payment_methods#destroy", as: :remove_card
  get '/cards' => "payment_methods#cards", as: :cards
  post "/bank_account" => "payment_methods#add_bank_account", as: :add_bank_account
  get "/bank_account/:id" => "payment_methods#bank_account", as: :bank_account
end

app/views/admin/_book.html.erb
<% @books.each do |book| %>
  <div class="list is-hoverable">
    <div class="list-item">
      <div class="columns">

        <div class="column">
          <%= book.title %>
        </div>

        <div class="column">
          <%= book.author %>
        </div>

         <div class="column">
          <%= book.created_at.strftime("%d/%m/%Y, %H:%M") %>
        </div>

        <div class="column is-2">
          <%= link_to book_path(book), method: :delete, title: "delete book", data: { confirm: "Are you sure "} do %>
            <span class="is-pulled-right"><i class="fa fa-times fa" aria-hidden="true"></i></span>
          <% end %>

          <%= link_to book_path(book) do %>
            <span class="is-pulled-right"><i class="fa fa-eye" aria-hidden="true"></i></span>
          <% end %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/_menu_tabs.html.erb
<div class="tabs is-large is-centered">
  <ul>
    <li class="is-active">
      <%= link_to products_path  do %>
        <span class="icon is-small"><i class="fa fa-image" aria-hidden="true"></i></span>
        <span>Products</span>
      <% end %>
    </li>
    <li>
       <%= link_to plans_path  do %>
        <span class="icon is-small"><i class="fa fa-money" aria-hidden="true"></i></span>
        <span>Plans</span>
      <% end %>
    </li>
    <li>
       <%= link_to books_path  do %>
        <span class="icon is-small"><i class="fa fa-book" aria-hidden="true"></i></span>
        <span>Books</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/admin/books.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <h1 class="title is-3">Books</h1>
    </div>
  </div>
</div>

<div class="columns is-centered">
  <div class="column is-6">
    <div class="list is-hoverable">
      <div class="list-item">
        <div class="columns">

          <div class="column is-4">
            <p class="sub-text">Title</p>
          </div>

          <div class="column is-3">
            <p class="sub-text">Author</p>
          </div>

          <div class="column is-4">
            <p class="sub-text">CREATED</p>
          </div>

          <div class="column is-4">
             <p></p>
          </div>
        </div>
    </div>

  <%= render "book" %>
</div>

app/views/admin/dashboard.html.erb
<%= render "menu_tabs" %>