config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'home', to: "home#index"
  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'admin', to: 'admin#dashboard'
  get 'admin/books', to: 'admin#books'

  get 'dashboard', to:'user_dashboard#dashboard'
  get 'dashboard/purchases', to: "user_dashboard#purchases"

  get 'generate', to: "bills#generate", as: :generate_bill

  resources :products
  resources :plans
  resources :charges, only: [:new, :create]

  get 'payment_success', to: "charges#success", as: :success_payment

  get  'pricing', to: "pricing#index", as: :pricing
  resources :subscriptions

  get '/card/new' => "payment_methods#new_card", as: :add_payment_method
  post "/card" => "payment_methods#create_card", as: :create_payment_method
  get '/card/:id' => "payment_methods#show", as: :card
  delete '/card/:id' => "payment_methods#destroy", as: :remove_card
  get '/cards' => "payment_methods#cards", as: :cards
  post "/bank_account" => "payment_methods#add_bank_account", as: :add_bank_account
  get "/bank_account/:id" => "payment_methods#bank_account", as: :bank_account
end

app/controllers/user_dashboard_controller.rb
class UserDashboardController < ApplicationController
  def dashboard
    @payment_method = current_user.payment_methods.last
    @charge = Charge.last
  end

  def purchases
    @purchases = current_user.books
  end
end

app/views/user_dashboard/_menu.html.erb
<div class="tabs is-large is-centered">
  <ul>
    <li>
      <%= link_to subscriptions_path do %>
        <span class="icon is-small"><i class="fa fa-image" aria-hidden="true"></i></span>
        <span>Subscriptions</span>
      <% end %>
    </li>
    <li>
       <%= link_to cards_path do %>
        <span class="icon is-small"><i class="fa fa-money" aria-hidden="true"></i></span>
        <span>PaymentMethods </span>
      <% end %>
    </li>
    <li>
      <%= link_to dashboard_purchases_path do %>
        <span class="icon is-small"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>
        <span>Purchases</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/user_dashboard/_purchase.html.erb
<% @purchases.each do |purchase| %>
  <div class="list is-hoverable">
    <div class="list-item">
      <div class="columns">

        <div class="column">
          <%= purchase.title %>
        </div>

         <div class="column is-2">
          <%= purchase.created_at.strftime("%d.%m.%Y") %>
        </div>

         <div class="column">
            <%= link_to "file", purchase.document.url, { download: purchase.document_file_name } %>
        </div>

        <div class="column">
          <%= link_to book_path(purchase) do %>
            <span class="is-pulled-right"><i class="fa fa-eye" aria-hidden="true"></i></span>
          <% end %>
        </div>

      </div>
    </div>
<% end %>

app/views/user_dashboard/dashboard.html.erb
<%= render "menu" %>
<%#= link_to "Download Receipt", generate_bill_path(id: @charge.id, format: :pdf) %>

<!--
<%= simple_form_for :search, url: books_path, method: "GET" do |f| %>
  <%= f.input :flavors, label: "Category",  collection: Book.pluck(:title), as: :check_boxes %>
  <%#= f.input :strengths, label: "Flavor", collection: $flavors, as: :check_boxes  %>
  <%= f.submit "Search", class: "btn btn-primary m" %>
  <%= link_to "Reset", root_path  %>
<% end %>
 -->

app/views/user_dashboard/purchases.html.erb
<%= render "user_dashboard/menu" %>

<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <h1 class="title is-3">Purchases</h1>
    </div>
  </div>
</div>

<div class="columns is-centered">
  <div class="column is-6">
    <div class="list is-hoverable">
      <div class="list-item">
        <div class="columns">

          <div class="column is-3">
            <p class="sub-text">Title</p>
          </div>

          <div class="column is-2">
            <p class="sub-text">Bought(date)</p>
          </div>

          <div class="column is-2">
            <p class="sub-text">download</p>
          </div>

        </div>
    </div>
</div>

<%= render "purchase" %>