config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'home', to: "home#index"
  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'admin', to: 'admin#dashboard'
  get 'admin/books', to: 'admin#books'

  get 'dashboard', to:'user_dashboard#dashboard'
  get 'dashboard/purchases', to: "user_dashboard#purchases"

  get 'generate', to: "bills#generate", as: :generate_bill

  resources :products
  resources :plans
  resources :charges, only: [:new, :create]

  get 'payment_success', to: "charges#success", as: :success_payment

  get  'pricing', to: "pricing#index", as: :pricing
  resources :subscriptions

  get '/card/new' => "payment_methods#new_card", as: :add_payment_method
  post "/card" => "payment_methods#create_card", as: :create_payment_method
  get '/card/:id' => "payment_methods#show", as: :card
  delete '/card/:id' => "payment_methods#destroy", as: :remove_card
  get '/cards' => "payment_methods#cards", as: :cards
  post "/bank_account" => "payment_methods#add_bank_account", as: :add_bank_account
  get "/bank_account/:id" => "payment_methods#bank_account", as: :bank_account
end

app/models/product.rb
class Product < ApplicationRecord
  PRODUCT_TYPES = ["service", "good"]

  validates :name, presence: true
  has_many :plans
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_product_policy
  before_action :load_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.includes(:plans)
  end

  def new
    @product = Product.new
  end

  def create
    result = CreateProduct.call(product_params: product_params)

    if result.success?
      redirect_to result.product, notice: "Product was successfully created"
    else
      @product = Product.new(product_params)
      flash.now.alert = result.message
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    result = DestroyProduct.call(product: @product)

    if result.success?
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    else
      redirect_to result.product, alert: "#{result.message}"
    end
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :product_type, :stripe_id)
  end

  def check_product_policy
    redirect_to root_path, alert: "Access disable, only for admins" unless current_user.admin?
  end
end

app/views/products/_form.html.erb
<%= simple_form_for @product, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
    <div class="columns">

      <div class="column">

        <div class="field">
          <div class="control">
          <%= f.input :name, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, placeholder: "Book Library" %>
          </div>
        </div>


        <div class="field column is-4">
          <div class="control">
            <label class="label">Product Type:</label>
            <div class="control has-icons-left">
              <span class="select">
                <%= f.input_field :product_type, collection: Product::PRODUCT_TYPES, prompt: "Select a product type" %>
              </span>
              <span class="icon is-small is-left">
                <i class="fa fa-briefcase"></i>
              </span>
            </div>
          </div>
        </div>

  <%= f.button :submit, class: "button is-primary is-rounded" %>

<% end %>
</div>

app/views/products/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Editing Product</h1>
        <%= render 'form', product: @product %>
      </div>
    </div>
  </div>
</section>

app/views/products/index.html.erb
<%= render "admin/menu_tabs"%>

<div class="columns is-centered">
  <div class="column is-4">

  <% @products.each do |product| %>
    <div class="list is-hoverable">
      <div class="list-item">
      <%= link_to product.name, product_path(product) %>

      <%= link_to product_path(product), method: :delete, title: "delete product", data: { confirm: "Are you sure "} do %>
        <span class="is-pulled-right"><i class="fa fa-trash fa" aria-hidden="true"></i></span>
        <% end %>

      <%= link_to edit_product_path(product), title: "edit product" do %>
        <span class="is-pulled-right"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <h1 class="title is-3">Create new product</h1>
        <%= render 'form', product: @product %>
      </div>
    </div>
  </div>
</section>

app/views/products/show.html.erb
<section class="section">
  <div class="columns is-centered">

    <div class="column is-6 product-section">
      <p class="is-pulled-right">PRODUCT</p>
      <p class="title is-5"><%= @product.name %>
      </p>
      <%= link_to "Add pricing plan", new_plan_path(product_id: @product), class: "button is-link is-outlined" %>
    </div>
  </div>

  <div class="columns is-centered">
    <div class="column is-6 product-section">
      <p class="title is-5">Details

        <%= link_to product_path(@product), method: :delete, title: "delete product", data: { confirm: "Are you sure "} do %>
          <span class="is-pulled-right"><i class="fa fa-trash fa" aria-hidden="true"></i></span>
        <% end %>

        <%= link_to edit_product_path(@product) do %>
          <span class="is-pulled-right"><i class="fa fa-pencil" aria-hidden="true"></i></span>
        <% end %>

      </p>

      <hr/>

      <div class="columns">
        <div class="column is-2">
          <p>Name</p>
        </div>
        <div class="column">
          <%= @product.name %>
        </div>
      </div>

      <div class="columns">
        <div class="column is-2">
          <p>Type</p>
        </div>
        <div class="column">
          <%= @product.product_type %>
        </div>
      </div>

      <div class="columns">
        <div class="column is-2">
          <p>Created</p>
        </div>
        <div class="column">
          <%= @product.created_at.strftime("%d/%m/%Y, %H:%M")%>
        </div>
      </div>

      <div class="columns">
        <div class="column is-2">
          <p>Stripe ID</p>
        </div>
        <div class="column">
          <%= @product.stripe_id%>
        </div>
      </div>
    </div>
  </div>

  <div class="columns is-centered">
    <div class="column is-6 product-section">
      <p class="title is-5">Pricing plans</p>
      <hr/>

      <% @product.plans.each do |plan|%>
        <%= link_to plan_path(plan) do %>
          <div class="columns">

            <div class="column">
              <%= plan.nickname %>
              <%= plan.currency %> <%= plan.amount %> / <%= plan.interval %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</section>